# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/GlenHani/Intro_to_the_web.git" }

gem 'capybara'
gem 'selenium-webdriver'
gem 'rspec'
gem 'sinatra'
gem 'shotgun'
